### ISSUE TITLE
Improve the buttons CSS classes usage

### ISSUE THREAD

**Issue by afercia** [swissspidy/preferred-languages#10]
Hello. The core buttons CSS classes should be used as "stackable" classes, meaning `.button` is the base class and then the other ones can be added as modifiers. 

Worth noting the `.button-secondary` class is deprecated and it's there just for backward compatibility.

More importantly, some things, for example the focus style and responsiveness, will work properly just when using the "stackable" approach. For example:

Bad, because it doesn't reset `outline` and it's not responsive:
`<button type="button" class="button-secondary">Button</button>`
Better:
`<button type="button" class="button">Button</button>`

Same for primary buttons, although they're not used in the plugin, it's worth mentioning:

Bad:
`<button type="button" class="button-primary">Button</button>`
Better:
`<button type="button" class="button button-primary">Button</button>`

Quoting from the inline comment in `buttons.css`:
```

WordPress-style Buttons
=======================
Create a button by adding the `.button` class to an element. For backward
compatibility, we support several other classes (such as `.button-secondary`),
but these will *not* work with the stackable classes described below.

Button Styles
-------------
To display a primary button style, add the `.button-primary` class to a button.
```

The effect of `button-secondary` not resetting `outline` is particularly evident in webkit browsers on macOS, see below a quick comparison in the responsive view (they're also bigger in the responsive view):

<img width="462" alt="screen shot 2017-05-20 at 14 09 24" src="https://cloud.githubusercontent.com/assets/1682452/26275685/8ed4c248-3d66-11e7-9d98-9b7cb81340fd.png">

**Comment by swissspidy** [comment]
Thanks @afercia! I replaced the `button-secondary` class with `button` now. Anything else I missed here or should I consider this being fixed?

**Comment by afercia** [comment]
Nothing else, I think. Thanks!
