### ISSUE TITLE
WPML String Translations Bug

### ISSUE THREAD

**Issue by srueegger** [swissspidy/preferred-languages#139]
Hallo zusammen

Ich habe einen Bug mit dem Plugin in Kombination mit dem WPML String Translation Plugin gefunden.

Mit der Version 3.0 von String Translations wurde String Translations etwas überarbeitet. Die übersetzen Strings werden nun in einer mo-Datei gespeichert.

Wenn "Prefered Languages" aktiviert ist, werden dann nicht mehr alle Strings übersetzt. Die einzige Lösung die ich bisher gefunden habe ist - Prefered Languages zu deaktivieren.

**Comment by swissspidy** [comment]
Danke für den Hinweis 👍 

Ich würde vorschlagen dies WPML zu melden, da es ein kommerzielles Plugin ist und ich das nicht testen kann. Das String Translations Plugin scheint tief ins System einzugreifen, was Konflikte unvermeidbar macht. Das WPML-Team hat da sicher mehr Ressourcen als ich mit meiner bescheidenen Freizeit um dies zu testen :-) Jegliche Hilfe hierzu ist natürlich gern gesehen.
