### ISSUE TITLE
Preferred Languages not saved

### ISSUE THREAD

**Issue by zu** [swissspidy/preferred-languages#21]
When saving the languages it doesn't save them (on a local install with LOCAL by Flywheel and WooCommerce activated). I don't see why.

![preferred-languages-1](https://user-images.githubusercontent.com/147629/31075029-c701be56-a773-11e7-8513-880291636886.png)

![preferred-languages-2](https://user-images.githubusercontent.com/147629/31075031-cb979e72-a773-11e7-9238-1a091bb72271.png)

**Comment by swissspidy** [comment]
Good catch!

There was an error in the JavaScript that prevented the hidden input field from properly storing the list of preferred languages.

Can you give the updated version a try? Download: [preferred-languages.1.0.1-beta.zip](https://github.com/swissspidy/preferred-languages/files/1348791/preferred-languages.1.0.1-beta.zip)

**Comment by zu** [comment]
Thanks!
Seems to work now, but looks a little strange (move up / down buttons below languages and not marked)

![preferred-languages](https://user-images.githubusercontent.com/147629/31076922-d38d7ad0-a77c-11e7-809e-d4061ee9be3b.png)


Also it seems there is either a German (Schweiz) translation file without the translation or something else is weird as if de_ch is the most preferred language, text on the configuration is english:

![preferred-lang-en](https://user-images.githubusercontent.com/147629/31077016-395d2234-a77d-11e7-907f-50cc6cb9ee6c.png)

**Comment by swissspidy** [comment]
> Seems to work now, but looks a little strange (move up / down buttons below languages and not marked)

Whoops, looks I forgot to include a CSS file. Here's the updated zip file: 
[preferred-languages.1.0.1-beta.zip](https://github.com/swissspidy/preferred-languages/files/1348853/preferred-languages.1.0.1-beta.zip)

> Also it seems there is either a German (Schweiz) translation file without the translation or something else is weird as if de_ch is the most preferred language, text on the configuration is english:

Yeah I just noticed this as well. There's a de_DE translation for the plugin, but it's not loaded. The reason is the just-in-time loading of translations in WordPress. When a plugin doesn't call `load_plugin_textdomain()` themselves (like this one), the fallback mechanism doesn't work. See #22.

**Comment by zu** [comment]
Seems like always this kind of things are more complex as they should be ;-)

**Comment by zu** [comment]
CSS loads and design looks very good now ;-)

**Comment by zu** [comment]
The plugin version is still 1.0.0 so for release a next (beta) version, you should update this too ;-)
