### ISSUE TITLE
Fallback for single translations?

### ISSUE THREAD

**Issue by tyrann0us** [swissspidy/preferred-languages#210]
Hi, great plugin!

If I understand the plugin correctly, it works like this:
1. WordPress languages have been set to German (Swiss), German (Formal)
2. "Plugin A" has been completely translated to German (Formal) and German (Swiss)
3. "Plugin B" has been completely translated to German (Formal) but not to German (Swiss)
4. For "Plugin A", Preferred Languages does nothing
5. For "Plugin B", Preferred Languages tells WordPress to fallback to German (Formal)

Is this correct?

Does the following work too?
1. WordPress languages have been set to German (Swiss), German (Formal)
2. "Plugin A" has been completely translated to German (Formal) and German (Swiss)
3. "Plugin B" has been completely translated to German (Formal) but not to German (Swiss)
4. **"Plugin C" has been completely translated to German (Formal) but _only partially_ to German (Swiss)**
4. For "Plugin A", Preferred Languages does nothing
5. For "Plugin B", Preferred Languages tells WordPress to fallback to German (Formal)
6. **For "Plugin C", Preferred Languages tells WordPress to fallback to German (Formal) _only for the missing translations_**

In my tests, the second scenario did not work. Also, If I read the code correctly, it is not supported. Can you confirm this?

Thanks!

**Comment by tyrann0us** [comment]
@swissspidy, can you confirm that the behaviour described in the second scenario does not work? And if so, do you have plans to implement this (if technically possible)?

Thanks!

**Comment by jwittorf** [comment]
Hi @tyrann0us, seems like you are actively using the plugin (I've just stumbled upon it due to [this](https://wordpress.org/support/topic/is-this-plugin-compatible-with-wpml-10/)). My current project is still in development and therefore uses the most current WordPress, WooCommerce and WPML versions. Have you encountered any issues with recent plugin versions (if using them)?

Sorry for dropping in out of nowhere 😅

**Comment by tyrann0us** [comment]
@jwittorf, the plugin works great for us (as in: scenario 1 works). But we don't use WPML, so I can't say anything about it.

**Comment by jwittorf** [comment]
Thanks for your quick response! I just gave it a shot, seems to work with WPML :) One needs to disable the "Language Fallback" plugin if it was used before.

I might be getting your "case 7", as I understand that I the behaviour you would be expecting: take the fallback only where needed and use the first priority everywhere else. Since this doesn't seem to be the case: what happens currently in scenario 2?

**Comment by tyrann0us** [comment]
WordPress uses English (the language used in the source code) for untranslated strings. Basically as if the "Preferred Languages" is not active.

**Comment by swissspidy** [comment]
@tyrann0us To answer your questions:

> "Plugin C" has been completely translated to German (Formal) but only partially to German (Swiss)

We need to clarify what "partially" means. Is there a German (Swiss) language pack for "Plugin C" installed on your site or not?

Language packs are usually only generated and downloaded if they are >90% complete.

If you want the German (Swiss) language pack even if it's only 10% complete and thus missing on your site, you'd need to use a plugin like https://wordpress.org/plugins/translation-tools/.

> For "Plugin C", Preferred Languages tells WordPress to fallback to German (Formal) only for the missing translations

This is not currently supported, however is being explored in #41

**Comment by tyrann0us** [comment]
@swissspidy, thanks for your response.
>We need to clarify what "partially" means. Is there a German (Swiss) language pack for "Plugin C" installed on your site or not?

We use custom client-specific plugins which we translate with Loco Translate. So language packs live in `wp-content/plugins/custom-plugin/languages/` and can be very incomplete (e.g. only 10% translated).

>This is not currently supported, however is being explored in #41

Ah! I totally missed that issue when searching for similar issues. So this is a duplicate.
