### ISSUE TITLE
it's not possible to add another language

### ISSUE THREAD

**Issue by zu** [swissspidy/preferred-languages#25]
![preferred-languages](https://user-images.githubusercontent.com/147629/31327434-7feed5a6-accf-11e7-92e8-b1251576f4b4.png)

I don't know why or what happened here but I couln't add another language here (local environment).

It was not possible to select a language.
"Hinzufügen" (Add) switched to Afrikaans (obviously the first language in the list) and this could be added. After removing this language, it was possible to choose any language but when it was added it switched back to inactive-locales-controls

**Comment by chantalcoolsma** [comment]
Seeing this too. Sometimes it happens after adding one language, sometimes after adding a second language. Not a reproducible pattern.

**Comment by swissspidy** [comment]
I just made bunch of changes to the JS, would you mind giving the current version a shot? Here's the ZIP file: [preferred-languages.zip](https://github.com/swissspidy/preferred-languages/files/1372633/preferred-languages.zip)

It's really tough when one cannot reproduce a bug properly, so I appreciate any more details I can get :-)

Did you have some languages in the list already when you opened the page and started adding/removing languages?
What browser are you using?

**Comment by zu** [comment]
After reinstalling the plugin the before installed and added languages where gone.
I added them all again.

After that the list of languages was deactivated and I had the same situation as before. I could add a language (Afrikaans) that was selected bur greyed out and then remove it and all worked as expected.

It's on a local (LOCAL by flywheel dev environment) and although I  defined the selfsigned certificate as trustworthy Chrome didn't think the site was secure. This might also have an influence.

**Comment by zu** [comment]
One more thing to mention: the language list distinguihes between installed and available languages. I added all installed languages before the problem happened. So there where no more installed languages I did not add.

**Comment by swissspidy** [comment]
> One more thing to mention: the language list distinguihes between installed and available languages. I added all installed languages before the problem happened.

Ah! 💡 

Now I think I have found the bug. Changes: https://github.com/swissspidy/preferred-languages/compare/ca4c2bd60d09d1b7b4ecd38d0d73af7adebfa243...94d03c3b1f1a676b5303c6d1b50eaeea79da19fd

Please test: [preferred-languages.zip](https://github.com/swissspidy/preferred-languages/files/1375034/preferred-languages.zip)

**Comment by zu** [comment]
Hallo Pascal


Sowohl LOCAL als auch auf einem Cloud-Server hat die Installation und Einrichtung tiptopp geklappt.




--\|/--------------------------------
  Christian Zumbrunnen
  Holzmatt 7, 5200 Brugg
  Mobile: 079 784 52 37
  Twitter: @chzumbrunnen

**Comment by pnoeric** [comment]
Hi Pascal, FYI I installed the master today and it failed on a new site, no languages list so adding a new language didn't work. Then I tried the version above (with "Ah! 💡") and that worked.

**Comment by swissspidy** [comment]
Thanks @pnoeric! I'll release the new version on WordPress.org in a bit.
