### ISSUE TITLE
Using v1.2.0 - not translating strings

### ISSUE THREAD

**Issue by pnoeric** [swissspidy/preferred-languages#26]
I have this code, for some reason it won't translate with v1.2.0 from the WP plugin repo. However, when I use the test version from the other thread (that I mentioned yesterday), the bug is fixed. So just want to confirm that 1.2.0 is NOT the latest version, and you've pushed this test code up to Wordpress and we're waiting on 1.2.x? :-)

In the meantime I'm using that test version on a live site.

```
    <div class="excerpt comment-content">
        <a href="<?= the_permalink( $post->post_parent ); ?>"><?php
            echo __( "Go to", 'rebelvideo' );
            echo ' ' . get_the_title( $post->post_parent ) . ' ';
            echo __( "portrait page", 'rebelvideo' ); ?></a>
    </div>

```

**Comment by swissspidy** [comment]
The version from https://github.com/swissspidy/preferred-languages/issues/25#issuecomment-335753750 is identical to version 1.2.0 from WordPress.org except for a renamed variable in JavaScript and a different version number in the PHP code. There were no changes in the translation loading logic between 1.1.0 and 1.2.0.

Where is the `rebelvideo` text domain coming from? Where are the translations stored? https://wordpress.org/plugins/rebelvideo/ doesn't exist, so I doubt that there are any translation files inside `wp-content/languages` for this text domain.

What are the contents of the `preferred_languages` option / usermeta?

**Comment by swissspidy** [comment]
@pnoeric Ping 🙂 Without more information I'm afraid I have to close this one.
