### ISSUE TITLE
Don't load on front end (aka Polylang Compatibility)

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/preferred-languages#29]

**Comment by daveloodts** [comment]
Hi @swissspidy, wondering if this project is still running. Still think it's an amazing idea for WordPress and to share translations over communities. Is there anything i can help to continue this?

**Comment by swissspidy** [comment]
@daveloodts It is :-) I just haven't had much time in the last few months to work on it. Also, there aren't many issues left.

There's #28, which basically means I need to undo some previous changes of mine.

The rest is basically testing, testing, testing. That means not only unit or integration tests, but also using the plugin on a site to see if everything works as expected.

**Comment by swissspidy** [comment]
FYI I just published a new version of the plugin yesterday.

Unfortunately I can't remember why I originally created this specific issue here about Polylang compatibility... In yesterday's testing I couldn't find any issues with Polylang or on the front end in general. Perhaps I have to test things with more complex setups.

**Comment by swissspidy** [comment]
What I noticed today:

When using a fallback like de_DE -> en_US and using Polylang to show a site in English, strings were displayed in German still.

So I guess that's the bug :-)

**Comment by swissspidy** [comment]
Version 1.5.0 has now been released with this fix: https://wordpress.org/plugins/preferred-languages/
