### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/preferred-languages#32]
Tightly related to #31.

Would be great to have some tests to demonstrate how the fallback mechanism works and everything.

**Comment by daveloodts** [comment]
Tested the plugin on 3 sites, alround looks very nice. Thanks.
WooCommerce translation is okay, but for Gravity Forms and Yoast SEO is saw some issues.

**Yoast SEO:**
Order: nl_nl, nl_be
![image 2018-07-20 at 10 18 52 am](https://user-images.githubusercontent.com/7976627/42991608-66a22dc0-8c06-11e8-8325-cca038ed1d77.png)

Order nl_be, nl_nl
![image 2018-07-20 at 10 23 00 am](https://user-images.githubusercontent.com/7976627/42991778-eeef2804-8c06-11e8-891b-c58880177ab6.png)
The word 'Zoek uiterlijk' is now becoming the english version, as the most part is nl_nl.
Another example of english:
![image 2018-07-20 at 10 25 10 am](https://user-images.githubusercontent.com/7976627/42991910-57a52f7e-8c07-11e8-8453-ceb2096fc7e5.png)

**Gravity Forms**
Order: nl_nl, nl_be
![schermafbeelding 2018-07-20 om 10 27 10](https://user-images.githubusercontent.com/7976627/42991992-932914e8-8c07-11e8-83b2-ff322c8f16f8.jpg)
This translation is okay, as GF is fully translated in nl_nl


order nl_be, nl_nl
![schermafbeelding 2018-07-20 om 10 27 30](https://user-images.githubusercontent.com/7976627/42992007-9de4d188-8c07-11e8-856f-885c45e0aacd.jpg)
GF is not translated in nl_be

I don't know how the preferation is being handled for Gravity Forms, as it stores the language files under it's own plugin folder. Does the 'preferred language' plugin only applies on the wp-content/languages folder?
