### ISSUE TITLE
Minimize prefered language.css

### ISSUE THREAD

**Issue by srueegger** [swissspidy/preferred-languages#35]
Hi

Thank you for your cool Plugin.
It's not a real Bug.

It even necessary to output the CSS file in the frontend? If so, can you minimize the file in a future version?

**Comment by swissspidy** [comment]
The CSS should definitely not load in the front end. I‘ll look into it. Thanks!

**Comment by swissspidy** [comment]
@srueegger CSS is now only enqueued in the admin. It has always been minimized though, so not sure what you meant there.

Will publish the new version 1.4.0 with this bug fix soon.

**Comment by srueegger** [comment]
@swissspidy - Thank You!
