### ISSUE TITLE
Keyboard event listeners triggering on other input fields

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/preferred-languages#38]
I can't edit my profile because the keyboard event listeners are triggered anywhere, even on completely unrelated fields.

**Comment by maximejobin** [comment]
What is the plan for the release of 1.5.0 ? Is it a matter of days/weeks/months ?

**Comment by swissspidy** [comment]
@maximejobin Why do you ask? :-) It depends on what kind of issues I wanna solve. If it‘s just the keyboard shortcuts: days. Otherwise a bit more.

**Comment by maximejobin** [comment]
We want to use it on a production website and saw you made a fix here. The question we had was: is it already pushed to the WP repo so we wait for the update ? Or do we update it manually because the actual "backspace" behavior is really problematic.

**Comment by swissspidy** [comment]
@maximejobin Makes sense. If you can quickly test the current build here I'll happily publish it on WordPress.org afterwards.

Basically you couldn't properly use the A key, backspace, or arrow keys anywhere else in your user profile. This is fixed now.

Download: [preferred-languages-1.5.0.zip](https://github.com/swissspidy/preferred-languages/files/2469143/preferred-languages-1.5.0.zip)

**Comment by jfarsen** [comment]
Hi, I've tried the 1.5 patched version and it seems to solve that specific issue (backspace), thanks!

**Comment by swissspidy** [comment]
Awesome, thanks for testing!

I'm gonna add a changelog entry for another (unrelated) change (b1f0061ecfa4fabbb13b3b0a546f7f93ea35f10a) and then release it ASAP.

**Comment by swissspidy** [comment]
Version 1.5.0 has now been released: https://wordpress.org/plugins/preferred-languages/

Happy updating!
