### ISSUE TITLE
misses some texts

### ISSUE THREAD

**Issue by petijo** [swissspidy/preferred-languages#46]
I set as 1st language formal Dutch, and as fallback Dutch. Next in woocommerce there appears some English in confirmation e-mails to clients, which wasn't there before the plugin and Dutch was the language. And worse: after deactivating the plugin, and setting the language to Dutch again, the English is still there...

**Comment by swissspidy** [comment]
Hi there!

Happy to test more with WooCommerce, but your case sounds like something else is not working correctly. The plugin doesn’t change anything when it’s not activated. Did you make sure to update all translations? Maybe the Dutch translations for WooCommerce are incomplete.

**Comment by petijo** [comment]
First all woocommerce e-mails were in Dutch. I activated your plugin, set
language to informal Dutch, and as alternate Dutch. But then some letters
were in English. So your plugin changed something. Then I deactivated your
plugin, set the language to Dutch again, but the e-mails remain in English,
so the changes were not undone. Maybe a cache issue? I'll do some more
testing.

Op vr 25 jan. 2019 om 15:38 schreef Pascal Birchler <
notifications@github.com>:

**Comment by petijo** [comment]
Activated again with 1. Dutch formal - 2. Dutch. In Woocommerce several texts appear in English now, that were in Dutch before your plugin.  For instance a note on my check out page, confirmation e-mails.

**Comment by petijo** [comment]
Hi there, Are you working on it? My site is live, so a fix would be much
appreciated!

Op za 26 jan. 2019 om 15:28 schreef Peter Ritmeester <ritmeester@pzzl.com>:

**Comment by swissspidy** [comment]
@petijo Extensive testing with WooCommerce is still on my todo list, but I have a lot on my plate now. I cannot give you any guarantee as to when I might get to it as this is a personal project I develop in my spare time. Perhaps I can find some time on the weekend.

What I can already tell you for sure is that anything goes back to normal when deactivating the plugin. So if your emails are still in English after deactivating the plugin, the Dutch translation is likely incomplete.

**Comment by petijo** [comment]
I can send you two "payment received" e-mails, one before and one after.
The one before is in Dutch, the one after is in English...  So the Dutch
translation is not incomplete. As there is a private address in the email I
cannot post them in the forum, but I could send them to you privately.

Op di 29 jan. 2019 om 17:43 schreef Pascal Birchler <
notifications@github.com>:

**Comment by swissspidy** [comment]
When not using using the Preferred Languages plugin — are you using formal Dutch translations or regular Dutch translation? Check the locale of the site and the receiving user.

**Comment by vdwijngaert** [comment]
Experiencing the same thing here with nl_BE and nl_NL as a fallback. Will look into it!

**Comment by vdwijngaert** [comment]
Wait... I'm not sure, but after taking a peak at the code, I think there might be a misunderstanding about what this plugin does, and does not do.

In this case, we have a problem where nl_BE is the website locale. The WooCommerce translations are outdated for this locale, so we want to fall back to nl_NL when a certain string is not yet translated in nl_BE. Is this something this plugin attempts to address? 

By taking a look at the code, it's starting to feel like this plugin only offers the "fallback" mo file when the nl_BE.mo file does not exist for a certain domain. Is that correct?

**Comment by swissspidy** [comment]
> By taking a look at the code, it's starting to feel like this plugin only offers the "fallback" mo file when the nl_BE.mo file does not exist for a certain domain. Is that correct?

Correct. What you are looking for is an enhancement that is being tracked in #41 / #249.

**Comment by vdwijngaert** [comment]
Ha interesting. I'll check it out, see if I can help with something.

**Comment by swissspidy** [comment]
Closing this for now as there now is a `preferred_languages_merge_translations` filter. Will be in the next release.
