### ISSUE TITLE
Translation not loaded correctly

### ISSUE THREAD

**Issue by masteradhoc** [swissspidy/preferred-languages#466]
Hey @swissspidy 

Thanks for your work on this! After a lot time without issues i now seem to have found one. :)

1) installed woocommerce & woocommerce blocks from wp repo
2) installed your plugin with these settings configured
![image](https://user-images.githubusercontent.com/6242098/166255077-54cfed0c-9718-44be-96aa-01c9525005cf.png)
3) i still see some strings of woocommerce blocks in english as f.e. on the cart
"Proceed to checkout" as example
![image](https://user-images.githubusercontent.com/6242098/166255210-93c5093a-2fcf-4a93-a794-09bb954b1146.png)

4) let's check the flow of the strings.

step a (not found, correct): https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de-ch/informal/?filters%5Bterm%5D=proceed&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

step b (not found, correct): https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de-ch/default/?filters%5Bterm%5D=proceed&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

step c (not found, incorrect): https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de/default/?filters%5Bterm%5D=proceed&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

On Step C the translation should be found and shown.

Same also happens f.e. on "shipping method"
[Step A](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de-ch/informal/?filters%5Bterm%5D=shipping+method&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) -> [Step B](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de-ch/default/?filters%5Bterm%5D=shipping+method&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) -> [Step C](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de/default/?filters%5Bterm%5D=shipping+method&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)

Any Idea what could be the issue here?

**Comment by masteradhoc** [comment]
@swissspidy thanks! i checked this further and was not able to achieve what we wanted. I noticed with Preferred Languages and WooCommerce Blocks together activated we have this  issue
![image](https://user-images.githubusercontent.com/6242098/166890286-c1fdd6bd-6c8a-4dc3-9a2e-b020756c5228.png)
![image](https://user-images.githubusercontent.com/6242098/166890331-9884d444-18d4-4930-856d-6fd39a3c07c7.png)

here in code
`<script type='text/javascript'>
( function( domain, translations ) {
var localeData = translations.locale_data[ domain ] || translations.locale_data.messages;
localeData[""].domain = domain;
wp.i18n.setLocaleData( localeData, domain );
} )( "woo-gutenberg-products-block", {"translation-revision-date":"2022-05-05 07:29+0000","generator":"Loco https:\/\/localise.biz\/","source":"packages\/woocommerce-blocks\/build\/wc-payment-method-cheque.js","domain":"woocommerce","locale_data":{"woocommerce":{"":{"domain":"woocommerce","lang":"de_CH","plural-forms":"nplurals=2; plural=n != 1;"}}}} );
</script>`

see https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/woocommerce-gutenberg-products-block.php#L196

else we dont have this issue:
![image](https://user-images.githubusercontent.com/6242098/166890275-06d11c23-4db4-4b7d-9a70-8c49c76719da.png)

Any idea why we have this compatibility issue?

**Comment by swissspidy** [comment]
Can you tell me how to reproduce this issue? It is not clear to me how you got there.

I installed WooComerce, WooCommerce Blocks, configured a couple of preferred languages, inserted an "All Products" block and don't see any console errors on the frontend.

The code you shared shows that you manually translated WooCommerce yourself using Loco Translate. So maybe that's at fault here? The translation coming from Loco has the text domain "woocommerce" and not "woo-gutenberg-products-block", which causes the JavaScript error.

So you will need to look into that.

**Comment by masteradhoc** [comment]
@swissspidy Thanks! We deleted now all the translations and the locotranslate plugin.
when we got all the new translations once again and activated your filter we now see more translations as before. looks much better.

Question upfront: Why dont you activate this filter by default? I saw quite a lot plugin with small amount of translated strings for switzerland (as if someone had started and stopped then). Could be a interesting to have this as a default or is there any negative possibility (loading speed)?

--

2nd i dig a bit deeper into the still english texts with my setup (WooCommerce, Woo Blocks) and Language Priority (German (Swiss), German (Formal), German)

**CART PAGE Example**

![image](https://user-images.githubusercontent.com/6242098/167090708-8ae0a57b-a308-4777-8473-184b07bb4dc4.png)

1. [status waiting, not accepted yet](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de-ch/default/?filters%5Bterm%5D=Including&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)
2. [translated](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de/formal/?filters%5Bterm%5D=Including&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)

Doesnt it take the 2nd Prioirity if the status is on waiting?

**Another Example**
- "Remove item" is left at product list
![image](https://user-images.githubusercontent.com/6242098/167090456-a3a6f31c-34e5-4472-a6ea-2c2ec8164dd3.png)

same also here [Priority 1](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de-ch/default/?filters%5Bterm%5D=Remove+item&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) and [Priority 2](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de/formal/?filters%5Bterm%5D=Remove+item&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)

**Comment by swissspidy** [comment]
The filter is a relatively new addition. Enabling this by default would be a breaking change and not everyone might want this behavior. Having this filter makes this new behavior opt-in and allows us to gather more information about how well it works and performs. We may very well activate it by default in the future, depending on all the feedback we gather.

In short: time will tell.

As for the missing translation, not sure what's going on at first glance.

But as you can see at https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/woocommerce-gutenberg-products-block.php, which you pointed to, the WooCommerce Blocks plugin has some very custom logic for loading translations.

It is very likely that this custom logic is not compatible with the way Preferred Languages works. Especially if translations otherwise work fine for your other plugins.

In that case I recommend reaching out to them about fixing this.

**Comment by masteradhoc** [comment]
After new release of woo blocks seems to work fine now!
