### ISSUE TITLE
Disable select field on initial load when all languages are selected

### ISSUE THREAD

**Issue by ocean90** [swissspidy/preferred-languages#47]
When I add all installed languages I get a disabled select field like this:
<img width="487" alt="all-added" src="https://user-images.githubusercontent.com/617637/53189061-f1721500-3606-11e9-9cf7-edb0870b33c9.png">

But after the reload it's no longer disabled:
<img width="537" alt="not-disabled" src="https://user-images.githubusercontent.com/617637/53189144-20888680-3607-11e9-8e4c-0d8fc912d0ed.png">

**Comment by swissspidy** [comment]
Good catch!

In both cases, `Deutsch (Schweiz)` shouldn't be visible in the `<select>` either, because it's already in the list of preferred locales.

**Comment by ocean90** [comment]
Right, it has the class `hidden` but I guess because it's the first item in the list it will still be displayed.

**Comment by swissspidy** [comment]
@ocean90 I just added a fix for this in 6d4e1dce3a20ae4a5298d433d5b814ba4ffc9c56 if you wanna test it.

ZIP file of the current build: [preferred-languages-beta.zip](https://github.com/swissspidy/preferred-languages/files/2985341/preferred-languages-beta.zip)

**Comment by ocean90** [comment]
@swissspidy Thanks, it's working fine for me.
