### ISSUE TITLE
WPML Compatibility

### ISSUE THREAD

**Issue by maximejobin** [swissspidy/preferred-languages#51]
I went into a user profile and saw 7 boxes to ask user language preferences.

Here is a screenshot of the first 3 (there are all the same) :

![image](https://user-images.githubusercontent.com/1080760/54610837-36357400-4a2c-11e9-8915-8f665ab5b19a.png)

We use WordPress 5.0.x
WPML

Let me know if you need any debugging information or want me to dump something to help.

**Comment by swissspidy** [comment]
One can never have enough options 😅 

Sounds like an incompatibility with WPML. Does this still happen when you disable WPML?

Also, how many languages did you set up in WPML?

**Comment by maximejobin** [comment]
I have only 2 languages on the website. I cannot, unfortunately, disable any plugins on this site. I'll have to try to reproduce it on a development server.

**Comment by maximejobin** [comment]
Sorry for the long delay. This does not happen when WPML is disabled.

**Comment by swissspidy** [comment]
Thanks for confirming! Unfortunately I don‘t have a copy of WPML to test this with to find a good solution.

**Comment by maximejobin** [comment]
I can provide one. Email me : mjobin [a] satellitewp com

**Comment by maximejobin** [comment]
Hello Pascal,

Were you able to reproduce the problem with the provided license? Can I help in any way?

**Comment by swissspidy** [comment]
I'm afraid I haven't had time to work on this plugin in quite a while, so I didn't get around to test it so far. 😞

**Comment by maximejobin** [comment]
No worry!

**Comment by swissspidy** [comment]
Hi @maximejobin 

I finally got around to look into this!

There's now only one field being displayed when using WPML, not 20 😄 

Will release it soon.

**Comment by swissspidy** [comment]
WPML modifies the Settings screen like this:

![Screenshot 2021-07-10 at 11 22 34](https://user-images.githubusercontent.com/841956/125158402-32840900-e171-11eb-9dae-0a94919149d1.png)

Which obviously does not work with Preferred Languages:

![Screenshot 2021-07-10 at 11 22 43](https://user-images.githubusercontent.com/841956/125158406-3adc4400-e171-11eb-81eb-45588e26987b.png)

But not really something that can be done in PL.

For now I am closing this ticket.
