### ISSUE TITLE
Translations not "reloaded" when added to official repo

### ISSUE THREAD

**Issue by maximejobin** [swissspidy/preferred-languages#52]
The site is in "French Canada". It fallsback to "French".

I installed the plugin "Seriously Simple Podcasting". It had no translations for FR-CA so FR was downloaded and is used.

I went to the translation website and translated the plugin for FR-CA. It is at 100%. If I go to the update dashboard (even when forcing check), I don't see the FR-CA version and, therefore, it is not downloaded.

**Comment by swissspidy** [comment]
How long did you wait after adding the fr_CA translations? It usually takes a while until language packs are generated and then picked up by the update checks. Does it work fine after disabling the plugin?

I assume you had fr_CA translations installed for core itself already?

**Comment by maximejobin** [comment]
Several days passed.

I deactivated the plugin and tried to download translations but it still downloads FR-FR (not FR-CA). I first installed the website in English, then switched to FR-CA. Then installed your plugin and made FR as the fallback.

After deactivation, I still get only FR-FR. I went to the `languages` folder and removed manually all FR-FR files so that the dropdown in the admin section doesn't say that "FR-FR" is installed.

I still can't get the FR-CA as of now. Maybe the problem is not totally linked to your plugin. Still unclear to me.

Now, your plugin is uninstalled. I have deactivated the podcast plugin and reactivated it (couple of hours later). Still can't get the translations to be downloaded for FR-CA.

**Comment by swissspidy** [comment]
After deactivating the plugin, does the dropdown in the admin say `fr_CA` is installed? If not, language packs for that locale won't be downloaded. Maybe you can share a screenshot of these options or something.

**Comment by maximejobin** [comment]
It is both installed and selected. I only deleted fr_FR manually.

**Comment by tobifjellner** [comment]
I just had a look in the log of language pack generation for this plugin.
The first time a language pack was generated for fr_CA was on July 22, 2019. Before that, the translation status was at 94% for a while (i.e. just below the threshold). And some 2 weeks earlier, it was only 3%.

A language pack for a plugin is generated only when at least 95% of the strings in the "Stable plugin" sub project have been transated and also been approved by a translation editor.

**Comment by maximejobin** [comment]
When I opened the ticket, it was 100% translated. It still is by the way. 

@tobifjellner Can you confirm what I'm saying?

**Comment by tobifjellner** [comment]
Well. What I saw was that a language pack for fr_CA was created only on July 22nd. I.e. on July 16 there still was no langpack ready.
Did you translate "Dev" or "Stable"? It's stable that needs to be at 95% or more.

**Comment by tobifjellner** [comment]
I now had a look at the translation site and can confirm that you indeed finished the translation on July 15 (UTC). Probably some trigger got lost (happens now and then) and no packages were generated, until someone touched some strings for some other language one week later.

**Comment by maximejobin** [comment]
> Did you translate "Dev" or "Stable"? It's stable that needs to be at 95% or more.

Only stable.

**Comment by maximejobin** [comment]
@swissspidy Was it solved?

**Comment by swissspidy** [comment]
I figured after almost two years without activity this was likely not relevant anymore. Especially since it wasn't 100% clear what the issue is and whether it's caused by this plugin (it was mentioned that it also happens with the plugin being deactivated).

Happy to reopen if there's a reproducible bug caused by this plugin
