### ISSUE TITLE
Merging translations is slow

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/preferred-languages#536]
Maybe break out of loops when we know all translations have been filled in already.

**Comment by swissspidy** [comment]
Thought behind this:

With a list of preferred languages like `fr_FR,it_IT,de_CH,de_DE,es_ES`, and fr_FR being 100% translated, there is no need to load any it_IT,de_CH,de_DE,es_ES translations.

However, it is impossible to know whether fr_FR is actually fully translated, because the PO file only contains translated strings anyway.

**Comment by swissspidy** [comment]
Added a performance warning to the readme in 9912609ea538919d681304b306158359647fac04

**Comment by swissspidy** [comment]
@ocean90 perhaps you have some ideas here?

**Comment by swissspidy** [comment]
Ideally we improve the logic and performance so that it doesn‘t require a persistent object cache.

**Comment by pedro-mendonca** [comment]
Hi @swissspidy 
Would it make sense, and quicker, to use a JSON instead a PHP file?

**Comment by swissspidy** [comment]
@pedro-mendonca Loading and parsing JSON files is actually _much slower_ than straight out loading a PHP file. It's one of the reasons why core started converting `block.json` files to `block.php` files ([see this make/core post](https://make.wordpress.org/core/2022/10/07/improved-php-performance-for-core-blocks-registration/)). A PHP file can also be cached in OPcache, which has additional performance improvements.

You can see some initial results of this approach at #659.

That said, I am open to discuss and compare other approaches. I know that @ocean90 for example aims to explore different caching strategies for translations.

**Comment by pedro-mendonca** [comment]
Great to know, thanks :)

**Comment by swissspidy** [comment]
Related: https://make.wordpress.org/core/2023/07/24/i18n-performance-analysis/

With something like [Ginger MO](https://github.com/swissspidy/ginger-mo) this would become super fast. Plus, that library supports loading multiple translation files per domain, which is extremely useful.
Why? Instead of having to merge translations, Ginger MO would just automatically lookup strings in all of the loaded translation files.
