### ISSUE TITLE
JS Translations: Many calls to `is_readable`

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/preferred-languages#674]
The function ` preferred_languages_load_script_translation_file` calls `is_readable` ALOT. 

In my testing, it called, it around 1.5k times. 

![Screenshot 2023-04-26 at 15 45 18](https://user-images.githubusercontent.com/237508/234612969-a7755293-c070-4317-a18e-e885ae9867f5.png)

**Comment by swissspidy** [comment]
On which screen is this and what's your setup, i.e. what's your preferred languages list, active plugins, is translation merging enabled?

In my quick testing this function was not called that often.

I did find #676 though which definitely fixes a bug and should improve numbers.

**Comment by spacedmonkey** [comment]
- WordPress core development. 
- Plugins, this, web stories, CF7, Sitekit. 
- Language setup, En_UK, EN_Ca. 
- Used blackfire on web stories edit screen.

**Comment by swissspidy** [comment]
Thanks, that's already helpful!

While I don't get such high numbers, #676 does have quite an impact on the Web Stories edit screen.
