### ISSUE TITLE
Fallbacks not working any more since 2.0.0

### ISSUE THREAD

**Issue by krokodok** [swissspidy/preferred-languages#881]
Since the change from `$preferred_languages_textdomain_registry` to `$wp_textdomain_registry` the language fallback for themes is not working any more.

# How to reproduce
1. Install a clean WordPress.
2. Install Preferred Languages `1.8.0`.
3. Activate a theme of your choice.
4. Install two additional languages besides English, e.g. `it_IT` and `de_DE`. *Do this only for the core!*
5. Install only one of the two languages for the theme of your choice, e.g. `it_IT`.
6. Order the preferred languages in the settings like this:
    1. de_DE
    2. it_IT
7. The whole website will now be in German. The translatable strings of your theme will be in Italian because German is not available and the next available fallback language is Italian. A good place to check this is the heading of the comments section for a single post.
8. Switch to Preferred Languages `2.0.0` or `2.1.0`. 
9. The previously Italian string will now be in English, because the fallback is not working anymore.

# Code

The reason seems to be, that `$wp_textdomain_registry->get( $domain, $locale )` does not return a valid path anymore.

## 1.8.0
https://github.com/swissspidy/preferred-languages/blob/bac7a0f6eca600849ac033d9db3ed97125883064/inc/functions.php#L1035-L1039

## 2.0.0
https://github.com/swissspidy/preferred-languages/blob/ef93d0c4743fea06c994c72185d7f24d3dc5ec00/inc/functions.php#L964-L968

**Comment by swissspidy** [comment]
Heya, thanks a lot for your report!

I was able to locate the bug pretty quickly. The issue was that the previous version looped through all the preferred locales when checking the registry, whereas the new one didn't. A simple oversight I should have spotted.

A fix is available at #882. I just need to add some tests for it.

**Comment by swissspidy** [comment]
2.1.1 has now been released with this fix included. Thanks again!
