### ISSUE TITLE
The description of the plugin can't be translated via translate.wp.org

### ISSUE THREAD

**Issue by NekoJonez** [swissspidy/preferred-languages#883]
Like the title says. I looked for it and don't see how I can solve it by myself...

![image](https://github.com/swissspidy/preferred-languages/assets/4569581/fdc30727-228d-418b-b97b-f64797b97cb1)

**Comment by swissspidy** [comment]
Hiya, what do you mean exactly? Don‘t you see the string on the translate.wordpress.org site, or is it simply not being translated correctly? The screenshot doesn‘t show anything unusual.

**Comment by NekoJonez** [comment]
Heh, I thought I wrote more in my ticket... Seems I remeber things wrong.

Now, it isn't present in the translation platform. Usually when I notice things like these... I go into the code and look for the function that places the string. Yet, I think its in JS... And I dont know how translations work in there. Thats what that screenshot was.

Anyways, I was doing a lot of things at once when I made this issue... Sorry for the mess. Hopefully this comment clears it up, otherwise just ask. :)

**Comment by swissspidy** [comment]
This particular string can be translated here: https://translate.wordpress.org/projects/wp-plugins/preferred-languages/stable/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5117659&filters%5Btranslation_id%5D=52292624

Does that work for you?

**Comment by NekoJonez** [comment]
https://translate.wordpress.org/projects/wp-plugins/preferred-languages/stable/nl-be/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5117659&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc

It is translated, yet it refuses to show up translated on my websites... How would I best troubleshoot this? Remove the po/mo file and let it redownload?

**Comment by swissspidy** [comment]
Back at the computer now and I think I can now reproduce this issue. When Preferred Languages is active, the description on `wp-admin/plugins.php` is indeed not translated, even though a translation exists.

So yeah, looks like a bug after all!

I'll look into it!

**Comment by swissspidy** [comment]
Turns out this is a bug in the translation file generation on WordPress.org, not this plugin.

This happens because the plugin description is identical to a string used on the JS side, so WP.org ends up not adding the string to the `.mo` file.

I just opened https://meta.trac.wordpress.org/ticket/7376 and https://github.com/wp-cli/i18n-command/issues/376 to track this.

In the meantime I could work around this by slightly altering the plugin description.

**Comment by NekoJonez** [comment]
Interesting, I am curious to see the solution. :) 
Happy to help

**Comment by swissspidy** [comment]
In 2aeb0d7a1b34f85154a0f7f7c29e05646c58e83c I changed the plugin description, so with the next release this will be resolved (once it is translated by the community).

There's also https://github.com/wp-cli/i18n-command/pull/377 to potentially fix this for all plugins on dotorg with the same issue (probably not many)
