### ISSUE TITLE
Compatibility with Gutenberg plugin

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/preferred-languages#90]
Fallbacks don't seem to work when the Gutenberg plugin is active.

Perhaps because it does its own overloading:

https://github.com/WordPress/gutenberg/blob/a5b1b2e271a55a7474bdd803df490871252a2d39/lib/client-assets.php#L87-L154

**Comment by strarsis** [comment]
@swissspidy: Any workaround for this? The Gutenberg editor is in English on de_DE_formal sites and all the translated strings for de_DE_formal for Gutenberg are still pending. 😿

**Comment by swissspidy** [comment]
I haven't looked at this yet, so I don't know the exact cause that I'd need a workaround for :-)

Perhaps using `remove_filter( 'load_script_translation_file', 'gutenberg_override_translation_file', 10 );` at the right time helps.

**Comment by swissspidy** [comment]
@strarsis Turns out this was a bug in Gutenberg indeed, which is now fixed (https://github.com/WordPress/gutenberg/pull/17900). It will be included in the next Gutenberg release.
