### ISSUE TITLE
Prefered Languages User Settings owerwrites WPML User settings

### ISSUE THREAD

**Issue by marcoluzi** [swissspidy/preferred-languages#945]
Hey

First of all, thanks for that awesome plugin.
Recently I noticed a compatibility issue with WPML. WPML offers some user specifc settings, for example, you can display a hidden language for specific users. When Preferred Languages is activated these settings are not visible anymore. Could this be fixed, so that the plugins are compatible with each other?

![Screenshot 2024-02-21 at 08 23 02](https://github.com/swissspidy/preferred-languages/assets/40238681/7b16024d-8c58-4e04-8bac-09a4d289d0bf)

Thanks :)

**Comment by swissspidy** [comment]
Thanks for your report.

I thought I had fixed that once in the past, but looks like it got reintroduced. Will fix it again.
